FROM python:3.11

WORKDIR /app

# Copiar el archivo de dependencias e instalarlas
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del proyecto
COPY . .

# Instalar OpenSSL para generar claves SSL
RUN apt-get update && apt-get install -y openssl

# Copiar el script de inicio
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

# Comando para ejecutar la aplicación
CMD ["./start.sh"]
