version: '3.8'

services:
  web:
    build: .
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
