version: '3.8'

services:
  api:
    build: .
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs
    networks:
      - konnekt-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - konnekt-network

networks:
  konnekt-network:
    driver: bridge

volumes:
  mongodb_data: